// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jgliq0NMCgG9RzHWg2JhBKaxrz2526A',
    appId: '1:786108804212:web:dc90d2b882a6e38a727521',
    messagingSenderId: '786108804212',
    projectId: 'softphone-283aa',
    authDomain: 'softphone-283aa.firebaseapp.com',
    databaseURL: 'https://softphone-283aa-default-rtdb.firebaseio.com',
    storageBucket: 'softphone-283aa.appspot.com',
    measurementId: 'G-W4NMZZPM8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQRNNSGFj9byqQ3YgODQM4Cq3tX5xXvrU',
    appId: '1:786108804212:android:015369a15c81da86727521',
    messagingSenderId: '786108804212',
    projectId: 'softphone-283aa',
    databaseURL: 'https://softphone-283aa-default-rtdb.firebaseio.com',
    storageBucket: 'softphone-283aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBON2JqtSqYXNxOKGzKoO2UQAa2h7gxucA',
    appId: '1:786108804212:ios:11b989757baeb3e8727521',
    messagingSenderId: '786108804212',
    projectId: 'softphone-283aa',
    databaseURL: 'https://softphone-283aa-default-rtdb.firebaseio.com',
    storageBucket: 'softphone-283aa.appspot.com',
    iosBundleId: 'com.example.softphone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBON2JqtSqYXNxOKGzKoO2UQAa2h7gxucA',
    appId: '1:786108804212:ios:11b989757baeb3e8727521',
    messagingSenderId: '786108804212',
    projectId: 'softphone-283aa',
    databaseURL: 'https://softphone-283aa-default-rtdb.firebaseio.com',
    storageBucket: 'softphone-283aa.appspot.com',
    iosBundleId: 'com.example.softphone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jgliq0NMCgG9RzHWg2JhBKaxrz2526A',
    appId: '1:786108804212:web:2d906adb693f2bdd727521',
    messagingSenderId: '786108804212',
    projectId: 'softphone-283aa',
    authDomain: 'softphone-283aa.firebaseapp.com',
    databaseURL: 'https://softphone-283aa-default-rtdb.firebaseio.com',
    storageBucket: 'softphone-283aa.appspot.com',
    measurementId: 'G-S73ZLXE46F',
  );

}